### ISSUE TITLE
Multi-GPU support for MEMIT

### ISSUE THREAD

**Issue by jacklanda** [kmeng01/memit#5]
**[Issue desc]**
I've try to run MEMIT on the machine with 32GB GPU * 2 (Tesla V100), under the 10k edit number.
However, it fails, due to the large weight size(GPT-J-6B) and the data(even in small batch_size) could not be placed into single GPU instance.  

**[Comment for Emhancement]**
I would like to ask if there is an implementation on the support for Multi-GPU on MEMIT?
I mean the model could be placed in single one GPU, and every batches of data wich leveraged by model could be placed in another GPU. Overall, a Non-distributed 2 GPU(or more) training implementation.

**Comment by Elanmarkowitz** [comment]
I have developed multi-GPU support but am not yet able to share it, unfortunately.

If you want to develop yourself, there are three things that need to change
1) When loading the model from transformers use device="auto". 
2) When two tensors are on different devices, move one to the device of the other. i.e. `x = a + b` should be `b = b.to(a); x = a + b`. I generally identify what device the layer weights are on for the layer being edited and move all the tensors there. 
3) You may also need to cleanup some memory stuff if your GPUs are small. The GPU cleanup section in memit_main does not work as shown.
